### ISSUE TITLE
conda-forge::pyeda

### ISSUE THREAD

**Issue by lorenzleutgeb** [colomoto/colomoto-conda#10]
I added pyeda to conda-forge (https://github.com/conda-forge/staged-recipes/pull/27474).

See:
 - https://anaconda.org/conda-forge/pyeda
 - https://github.com/conda-forge/pyeda-feedstock
 - https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fpyeda

Regarding https://github.com/colomoto/colomoto-conda/issues/1#issuecomment-2313352821 by @thomas-sturm: The new package builds for osx-arm64. I do not have a machine to test, but I'll assume that it is functional on Apple Silicon until someone reports the contrary. Anyway, I'll try to support that platform.

@pauleve: It'd be great if you could check whether `conda-forge::pyeda` is a suitable replacement for `colomoto::pyeda`. If yes, consider using it or even joining me in maintaining. If not, please feel free to [report the issues](https://github.com/conda-forge/pyeda-feedstock/issues/new) you are running into. Thanks!

**Comment by pauleve** [comment]
That's an awesome news, thank you so much for having worked on this package!
I'll make the switch, and report any issue.
