### ISSUE TITLE
Switch to the official clingo packages

### ISSUE THREAD

**Issue by aurelien-naldi** [colomoto/colomoto-conda#4]
The Potassco team has recently added "official" clingo packages: https://anaconda.org/potassco/clingo
They seem to work fine: we should consider using these packages instead of self-compiled ones (thus to also use the potassco channel)

**Comment by pauleve** [comment]
Fixed by https://github.com/colomoto/colomoto-docker/commit/d47c2be6e789953f7c47f432a251908ac96de55b and commit 088fdbbc625451ab0db30429712aa85a7f436f05
(include image validation)
