### ISSUE TITLE
Moving casq conda recipe to this repo?

### ISSUE THREAD

**Issue by soli** [colomoto/colomoto-conda#9]
There is a casq recipe for conda [inside casq's repo](https://github.com/soli/casq/blob/master/conda/meta.yaml) and made by @aurelien-naldi at the time.
I think he used it to "publish" directly casq to https://anaconda.org/colomoto/casq

Would it make sense to move that recipe here?

Otherwise, is there a way I can get "authority" on the above anaconda thing so that I can publish myself? (no idea what this involves, but I guess it's probably easy enough to automate…)

**Comment by aurelien-naldi** [comment]
Yes it can be automated, I think that the colomoto-conda repo has the required GitHub CI config. It just needs an authentication token in the secret wallet.

I don't remember if the recipe needs to be updated manually or if it extracts version number and other metadata from the python packaging config.

**Comment by soli** [comment]
We've started discussing this in an [issue](https://github.com/colomoto/colomoto-docker/issues/139) on the colomoto-docker repo, I'll first try to put CaSQ on conda-forge (they have an automated system for updating the conda packages from the PyPI packages) since that could be a _generic_ solution. If that fails, then we'll see…
